### ISSUE TITLE
Id contains undefined

### ISSUE THREAD

**Issue by cwohlman** [andrasq/node-mongoid-js#5]
I'm sometimes getting ids that look like this:

`59a044090004d2undefined13c3c000001`

I think the issues is that sometimes hexFormat is called with a width that is smaller than the input string.

**Comment by andrasq** [comment]
@cwohlman see if PR #7 fixes the issues you're seeing.  Should fix the unit tests, the "undefined" in the id string and the occasional longer than 24 byte ids returned.

It seems some systems have, or are configured for, longer than 16 bit process ids, and the mongoid id layout doesn't deal well with that.  I changed `mongoid-js` to use just 16 bits of the process id (the least significant 16).

**Comment by cwohlman** [comment]
Looks like it should work, I'll quickly try it out in my project & let you know if I run into any issues.

**Comment by cwohlman** [comment]
Everything passed on my machine, though I don't think the process ids were above 16 bits anyway (in this particular case).

**Comment by andrasq** [comment]
great, thanks!  I'll merge in the PR, and publish it (version 1.1.3)

**Comment by cwohlman** [comment]
Awesome! Looking forward to it!

**Comment by cwohlman** [comment]
Closing since #7 fixes this.

**Comment by cwohlman** [comment]
@andrasq thanks for fixing this issue, definitely nice not to have to inline a fixed version of this package anymore.

**Comment by andrasq** [comment]
@cwohlman You're welcome, glad to help!
